### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by VikramTiwari** [twitterdev/twitter-python-ads-sdk#108]
Error log:
```
$ pip --no-cache-dir install twitter-ads
Collecting twitter-ads
  Downloading twitter-ads-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    flake8.reporter: module references __file__
    flake8.tests._test_warnings: module references __file__
    flake8.tests.test_integration: module references __file__
    
    Installed /private/var/folders/_f/95xpdnrx4yncxz91dt53mvfh0000gn/T/pip-build-UPAkUB/twitter-ads/.eggs/flake8-2.6.2-py2.7.egg
    Searching for pytest-runner
    Reading https://pypi.python.org/simple/pytest-runner/
    Downloading https://pypi.python.org/packages/9e/4d/08889e5e27a9f5d6096b9ad257f4dea1faabb03c5ded8f665ead448f5d8a/pytest-runner-2.11.1.tar.gz#md5=bdb73eb18eca2727944a2dcf963c5a81
    Best match: pytest-runner 2.11.1
    Processing pytest-runner-2.11.1.tar.gz
    Writing /var/folders/_f/95xpdnrx4yncxz91dt53mvfh0000gn/T/easy_install-Y4i_Ld/pytest-runner-2.11.1/setup.cfg
    Running pytest-runner-2.11.1/setup.py -q bdist_egg --dist-dir /var/folders/_f/95xpdnrx4yncxz91dt53mvfh0000gn/T/easy_install-Y4i_Ld/pytest-runner-2.11.1/egg-dist-tmp-dNualG
    zip_safe flag not set; analyzing archive contents...
    Copying pytest_runner-2.11.1-py2.7.egg to /private/var/folders/_f/95xpdnrx4yncxz91dt53mvfh0000gn/T/pip-build-UPAkUB/twitter-ads/.eggs
    
    Installed /private/var/folders/_f/95xpdnrx4yncxz91dt53mvfh0000gn/T/pip-build-UPAkUB/twitter-ads/.eggs/pytest_runner-2.11.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_f/95xpdnrx4yncxz91dt53mvfh0000gn/T/pip-build-UPAkUB/twitter-ads/setup.py", line 64, in <module>
        **extra_opts
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1116, in best_match
        dist = working_set.find(req)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 714, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (pycodestyle 2.2.0 (/usr/local/lib/python2.7/site-packages), Requirement.parse('pycodestyle<2.1,>=2.0'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_f/95xpdnrx4yncxz91dt53mvfh0000gn/T/pip-build-UPAkUB/twitter-ads/
```

Seems like a version conflict for deps. But why so? I have even tried using the source to no avail.

**Comment by VikramTiwari** [comment]
Running it with `virtualenv` works, but why such strong requirements for version? Not sure if the versions are static at older versions, but if so, then it's even worse practice.

**Comment by kosmox** [comment]
I am facing the same issue - any help ?

**Comment by VikramTiwari** [comment]
@kosmox Only way to do this right now is using `virtualenv` http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/

**Comment by boltronic** [comment]
Hi @kosmox and @VikramTiwari, 

Would you mind running `pip list` and pasting the results into this thread? That should help us figure out what might be happening.

Thanks much,

Mike

**Comment by VikramTiwari** [comment]
Here you go!

```
$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.10)
amqp (2.1.4)
appdirs (1.4.3)
arrow (0.10.0)
astroid (1.4.9)
avro (1.8.1)
Babel (2.3.4)
backports.functools-lru-cache (1.3)
beam (0.3.0)
billiard (3.5.0.2)
bingads (10.4.12)
blinker (1.4)
celery (4.0.2)
chardet (2.3.0)
click (6.6)
configparser (3.5.0)
contextlib2 (0.5.4)
cookies (2.2.1)
crcmod (1.7)
croniter (0.3.14)
cycler (0.10.0)
dill (0.2.6)
docutils (0.13.1)
email (4.0.2)
emoji (0.3.9)
enum34 (1.1.6)
facebookads (2.9.1)
flake8 (3.2.1)
Flask (0.11.1)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
future (0.16.0)
futures (3.0.5)
gapic-google-cloud-datastore-v1 (0.15.3)
gapic-google-cloud-error-reporting-v1beta1 (0.15.3)
gapic-google-cloud-logging-v2 (0.91.3)
gapic-google-cloud-pubsub-v1 (0.15.3)
gapic-google-cloud-spanner-admin-database-v1 (0.15.3)
gapic-google-cloud-spanner-admin-instance-v1 (0.15.3)
gapic-google-cloud-spanner-v1 (0.15.3)
gapic-google-cloud-speech-v1beta1 (0.15.3)
gapic-google-cloud-vision-v1 (0.90.3)
gapic-google-logging-v2 (0.10.1)
gapic-google-pubsub-v1 (0.10.1)
google-api-python-client (1.5.4)
google-apitools (0.5.8)
google-auth (0.9.0)
google-auth-httplib2 (0.0.2)
google-cloud (0.23.0)
google-cloud-bigquery (0.23.0)
google-cloud-bigtable (0.23.1)
google-cloud-core (0.23.1)
google-cloud-dataflow (0.5.5)
google-cloud-datastore (0.23.0)
google-cloud-dns (0.23.0)
google-cloud-error-reporting (0.23.1)
google-cloud-happybase (0.22.0)
google-cloud-language (0.23.1)
google-cloud-logging (0.23.1)
google-cloud-monitoring (0.23.0)
google-cloud-pubsub (0.23.0)
google-cloud-resource-manager (0.23.0)
google-cloud-runtimeconfig (0.23.0)
google-cloud-spanner (0.23.1)
google-cloud-speech (0.23.0)
google-cloud-storage (0.23.1)
google-cloud-translate (0.23.0)
google-cloud-vision (0.23.3)
google-gax (0.15.8)
googleads (5.3.0)
googleapis-common-protos (1.5.2)
googledatastore (6.4.1)
grpc-google-cloud-logging-v2 (0.90.0)
grpc-google-cloud-pubsub-v1 (0.14.0)
grpc-google-iam-v1 (0.11.1)
grpc-google-logging-v2 (0.10.1)
grpc-google-pubsub-v1 (0.10.1)
grpcio (1.2.0)
httplib2 (0.10.3)
imagesize (0.7.1)
isort (4.2.5)
itsdangerous (0.24)
Jinja2 (2.8)
kombu (4.0.2)
lazy-object-proxy (1.2.2)
luminol (0.3.1)
MarkupSafe (0.23)
matplotlib (2.0.0)
mccabe (0.5.3)
mock (2.0.0)
mysql-connector-python (1.0.12)
MySQL-python (1.2.5)
mysql-utilities (1.3.5)
numpy (1.11.2)
oauth2client (4.0.0)
oauthlib (2.0.1)
packaging (16.8)
pandas (0.19.1)
pbr (1.10.0)
pep8 (1.7.0)
pip (9.0.1)
ply (3.8)
proto-google-cloud-datastore-v1 (0.90.3)
proto-google-cloud-error-reporting-v1beta1 (0.15.3)
proto-google-cloud-logging-v2 (0.91.3)
proto-google-cloud-pubsub-v1 (0.15.3)
proto-google-cloud-spanner-admin-database-v1 (0.15.3)
proto-google-cloud-spanner-admin-instance-v1 (0.15.3)
proto-google-cloud-spanner-v1 (0.15.3)
proto-google-cloud-speech-v1beta1 (0.15.3)
proto-google-cloud-vision-v1 (0.90.3)
proto-google-datastore-v1 (1.3.1)
protobuf (3.0.0)
protorpc (0.11.1)
pyasn1 (0.2.3)
pyasn1-modules (0.0.8)
pyflakes (1.3.0)
Pygments (2.2.0)
pylint (1.6.5)
pymongo (3.4.0)
pyparsing (2.2.0)
PySocks (1.6.7)
python-dateutil (2.6.0)
python-gflags (3.1.1)
python-http-client (2.2.1)
pytz (2017.2)
PyYAML (3.12)
raven (5.32.0)
redis (2.10.5)
requests (2.13.0)
requests-oauthlib (0.8.0)
responses (0.5.1)
rq (0.7.1)
rq-dashboard (0.3.7)
rq-scheduler (0.7.0)
rsa (3.4.2)
schedule (0.4.2)
scipy (0.18.1)
sendgrid (3.6.3)
setuptools (34.3.3)
six (1.10.0)
slacker (0.9.30)
snowballstemmer (1.2.1)
Sphinx (1.5.3)
SQLAlchemy (1.1.4)
subprocess32 (3.2.7)
suds-jurko (0.6)
tensorflow (0.12.1)
termcolor (1.1.0)
uritemplate (3.0.0)
urllib3 (1.19.1)
vine (1.1.3)
virtualenv (15.1.0)
Werkzeug (0.11.11)
wheel (0.29.0)
wrapt (1.10.8)
xlrd (1.0.0)
xmltodict (0.10.2)
yapf (0.14.0)
yasm (0.0)
```

**Comment by knowyrrole101** [comment]
Any update to version conflict issue? I can't seem to get this running. Is there a version specific dependency? I can set a local python version but not sure which version I should be installing exactly.

Thanks!
