### ISSUE TITLE
Twitter API Call error: TwitterError({'Unknown error: {0}'.format(json_data)})

### ISSUE THREAD

**Issue by STANAPI** [twitterdev/twitter-python-ads-sdk#167]
Hi everyone,

I have encountered the below same error for the past few days. Could anyone advise on this? Thank you very much.

Erorr log below:
_________________________________________________________________________________________________________
The Twitter Analytics API Call encountered the following exception:
Traceback (most recent call last):
File "C:\STB\STAN_MG_API\Twitter\twitter\api.py", line 4883, in ParseAndCheckTwitter
data = json.loads(json_data)
File "C:\Python36-32\lib\json_init.py", line 354, in loads
return _default_decoder.decode(s)
File "C:\Python36-32\lib\json\decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Python36-32\lib\json\decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\STB\STAN_MG_API\Twitter\tw_page_timeline.py", line 89, in extract
response = api.GetStatus(i_dict['id_str']).AsDict()
File "C:\STB\STAN_MG_API\Twitter\twitter\api.py", line 842, in GetStatus
data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
File "C:\STB\STAN_MG_API\Twitter\twitter\api.py", line 4893, in _ParseAndCheckTwitter
raise TwitterError({'Unknown error: {0}'.format(json_data)})
twitter.error.TwitterError: {'Unknown error: '}

**Comment by ChidiChinob** [comment]
What is the value or type of "json_data"? Are you trying to decode a response from UTF8 to Unicode?

**Comment by smaeda-ks** [comment]
This is not related to our SDK and duplicated: https://github.com/bear/python-twitter/issues/580
Closing this.
