### ISSUE TITLE
flake8 Version Conflict in Python 2.7

### ISSUE THREAD

**Issue by itaya-im** [twitterdev/twitter-python-ads-sdk#181]
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-LHsQx5/twitter-ads/setup.py", line 70, in <module>
        **extra_opts
      File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 316, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 371, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1111, in best_match
        dist = working_set.find(req)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 715, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (mccabe 0.6.1 (/usr/local/lib/python2.7/site-packages), Requirement.parse('mccabe<0.6,>=0.2.1'))
```

flake8==3.7.7
pycodestyle==2.5.0
pyflakes==2.1.1
mccabe==0.6.1 

in Python2.7

**Comment by smaeda-ks** [comment]
See https://github.com/twitterdev/twitter-python-ads-sdk/pull/194

Closing.
