### ISSUE TITLE
Critical issue with Twitter Ads SDK Version 5.3.0

### ISSUE THREAD

**Issue by shaun10** [twitterdev/twitter-python-ads-sdk#221]
`2019-08-21 08:41:55,150 - process_twitter_ads_api - ERROR - 'Analytics' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "process_twitter_ads_api/main.py", line 465, in <module>
    main(DATE_LIST)
  File "process_twitter_ads_api/main.py", line 434, in main
    run_date, segmentation_name, segmentation_type
  File "process_twitter_ads_api/main.py", line 185, in produce_analytics_data
    LOGGER.info('async_stats_job (url):         {}'.format(async_stats_job_result['url']))
TypeError: 'Analytics' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "process_twitter_ads_api/main.py", line 465, in <module>
    main(DATE_LIST)
  File "process_twitter_ads_api/main.py", line 434, in main
    run_date, segmentation_name, segmentation_type
  File "process_twitter_ads_api/main.py", line 185, in produce_analytics_data
    LOGGER.info('async_stats_job (url):         {}'.format(async_stats_job_result['url']))
TypeError: 'Analytics' object has no attribute '__getitem__'`

Issue did not occur in SDK version 5.2.0

**Comment by shaun10** [comment]
PR #211 seems to be connected https://github.com/twitterdev/twitter-python-ads-sdk/pull/211

**Comment by smaeda-ks** [comment]
Hi @shaun10 

Sorry, I forgot to include the change in the release note but yes, you need to change `async_stats_job_result['url']` to `async_stats_job_result.url`.

I'll update the release note.

**Comment by smaeda-ks** [comment]
@shaun10 The release note has been updated to include this breaking change.
https://github.com/twitterdev/twitter-python-ads-sdk/releases

I'm closing this issue but let me know if you have other questions regarding this. Thanks for flagging this.
