### ISSUE TITLE
WebsiteCard save: Invalid media key error

### ISSUE THREAD

**Issue by QuidObscurum** [twitterdev/twitter-python-ads-sdk#250]
Hello! 
I can't upload a website card via twitter_ads v 6.1.0 and get the following error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/.../venv/lib/python3.6/site-packages/twitter_ads/http.py", line 70, in perform
    raise Error.from_response(response)
twitter_ads.error.BadRequest: <BadRequest object at 0x7fdc1ba826a8 code=400 details=[{'code': 'INVALID_MEDIA', 'message': 'Invalid media key: MediaKey(TweetImage,1232610948466331648)'}]>
```
Below is my code:

```
account = twitter_client.accounts(id=acc_id) 
# upload image
response = Request(
    account.client,
    'post',
    '/1.1/media/upload.json',
    params={
        'additional_owners': next(account.promotable_users()).user_id,
        'media_category': MEDIA_CATEGORY.TWEET_IMAGE
    },
    files={'media': (None, io.BytesIO(s3_image_read))},
    domain='https://upload.twitter.com'
).perform()  # returns code 200
website_card = WebsiteCard(account)
website_card.name = 'Simple Headline'
website_card.website_title = 'Simple Headline'
website_card.website_url = 'http://google.com'
website_card.media_key = response.body['media_key']
# the following method raises an error
website_card.save()

```
Is there any workaround? The upload works with twitter-ads v 5.1.1 with image_media_id instead of media_key

**Comment by QuidObscurum** [comment]
Apparently, you also need to upload the image to media library and then save a website card:
```
media_library = MediaLibrary(account)
media_library.name = "Name"
media_library.file_name = 'image.png'
media_library.media_key = response.body['media_key']
media_data = media_library.add()

website_card = WebsiteCard(account)
...
website_card.save()
```
