### ISSUE TITLE
Cannot run quick_start.py

### ISSUE THREAD

**Issue by jackMort** [twitterdev/twitter-python-ads-sdk#28]
```
    python quick_start.py

   Traceback (most recent call last):
  File "quick_start.py", line 17, in <module>
    account = client.accounts(ACCOUNT_ID)
    File "/home/jackmort/.virtualenvs/tw/local/lib/python2.7/site-packages/twitter_ads/client.py", line 89, in accounts
    return Account.load(self, id) if id else Account.all(self)
    File "/home/jackmort/.virtualenvs/tw/local/lib/python2.7/site-packages/twitter_ads/account.py", line 43, in load
    return Cursor(klass, request, init_with=[client])
    File "/home/jackmort/.virtualenvs/tw/local/lib/python2.7/site-packages/twitter_ads/cursor.py", line 29, in __init__
    self.__from_response(request.perform())
    File "/home/jackmort/.virtualenvs/tw/local/lib/python2.7/site-packages/twitter_ads/cursor.py", line 91, in __from_response
    self._collection.append(obj.from_response(item))
    File "/home/jackmort/.virtualenvs/tw/local/lib/python2.7/site-packages/twitter_ads/resource.py", line 43, in from_response
    value = response.get(name, None)
   AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by brandonblack** [comment]
Resolved in #29 courtesy of @jackMort
